services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v3.3.0
    container_name: 3x-ui
    restart: unless-stopped
    networks:
      - default
      - traefik
    volumes:
      - ./data:/etc/x-ui/
    ports:
      - 443:443
      # - 2053:2053
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
      - XUI_ENABLE_FAIL2BAN=false
      - XUI_SKIP_HSTS=true
      - XUI_INIT_WEB_BASE_PATH=/3x-ui
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.3x-ui.rule=Host(`$HOSTNAME`) && PathPrefix(`/3x-ui`)"
      - "traefik.http.routers.3x-ui.entrypoints=websecure"
      - "traefik.http.routers.3x-ui.service=3x-ui"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"

      - "traefik.http.routers.3x-ui-sub.rule=Host(`$HOSTNAME`) && PathPrefix(`/3x-ui-sub`)"
      - "traefik.http.routers.3x-ui-sub.entrypoints=websecure"
      - "traefik.http.routers.3x-ui-sub.service=3x-ui-sub"
      - "traefik.http.services.3x-ui-sub.loadbalancer.server.port=2096"

networks:
  traefik:
    external: true

